import { validateLevel, expectedCounts } from './level-contract.mjs';
export { expectedCounts } from './level-contract.mjs';

// loader.js — fetch exported level JSON (MERGER-PLAN §3). Generated by:
//   cargo run -p skyroads-cli -- export-json . web/assets
// web/assets is git-ignored (see NOTICE); web/demo/ will hold the original neon demo level (P8).

export async function loadIndex() {
  const res = await fetch('./assets/levels/index.json');
  if (!res.ok) throw new Error(`levels/index.json ${res.status} — run scripts/build-web.sh first`);
  return res.json();
}

export async function loadLevel(file) {
  const res = await fetch(`./assets/levels/${file}`);
  if (!res.ok) throw new Error(`${file} ${res.status}`);
  const level = await res.json();
  validateLevel(level);
  return level;
}

/** Pick level from ?level=NN (roadIndex), default 0. */
export async function loadRequestedLevel() {
  const idx = await loadIndex();
  if (!Array.isArray(idx.levels) || idx.levels.length === 0)
    throw new Error('levels/index.json has no levels — re-run the exporter');
  const want = Number(new URLSearchParams(location.search).get('level') ?? 0);
  const entry = idx.levels.find(l => l.roadIndex === want);
  if (!entry && Number.isFinite(want) && want !== 0)
    console.warn(`?level=${want} not in index — falling back to ${idx.levels[0].file}`);
  const chosen = entry ?? idx.levels[0];
  const level = await loadLevel(chosen.file);
  return { index: idx, entry: chosen, level };
}
