// loader.js — fetch exported level JSON (MERGER-PLAN §3). Generated by:
//   cargo run -p skyroads-cli -- export-json . web/assets
// web/assets is git-ignored (see NOTICE); web/demo/ will hold the original neon demo level (P8).

export async function loadIndex() {
  const res = await fetch('./assets/levels/index.json');
  if (!res.ok) throw new Error(`levels/index.json ${res.status} — run scripts/build-web.sh first`);
  return res.json();
}

export async function loadLevel(file) {
  const res = await fetch(`./assets/levels/${file}`);
  if (!res.ok) throw new Error(`${file} ${res.status}`);
  const level = await res.json();
  validate(level);
  return level;
}

/** Pick level from ?level=NN (roadIndex), default 0. */
export async function loadRequestedLevel() {
  const idx = await loadIndex();
  if (!Array.isArray(idx.levels) || idx.levels.length === 0)
    throw new Error('levels/index.json has no levels — re-run the exporter');
  const want = Number(new URLSearchParams(location.search).get('level') ?? 0);
  const entry = idx.levels.find(l => l.roadIndex === want);
  if (!entry && Number.isFinite(want) && want !== 0)
    console.warn(`?level=${want} not in index — falling back to ${idx.levels[0].file}`);
  const chosen = entry ?? idx.levels[0];
  const level = await loadLevel(chosen.file);
  return { index: idx, entry: chosen, level };
}

function validate(level) {
  if (level.version !== 1) throw new Error(`unsupported level version ${level.version}`);
  if (!Array.isArray(level.cells) || level.cells.length !== level.length)
    throw new Error(`cells length ${level.cells?.length} != declared ${level.length}`);
  for (const row of level.cells)
    if (row.length !== level.columns) throw new Error('row width mismatch');
}

/** Expected instance counts per geometry class — the adversarial gate compares these
 *  against what the scene actually instanced. Derived ONLY from the JSON. */
export function expectedCounts(level) {
  const shortTop = level.constants?.cubeShortTop ?? 100;
  const tallTop = level.constants?.cubeTallTop ?? 120;
  const c = { flat: 0, short: 0, tall: 0, tunnel: 0, nonEmpty: 0 };
  for (const row of level.cells) for (const cell of row) {
    const any = cell.tile || cell.tunnel || cell.cube != null;
    if (any) c.nonEmpty++;
    if (cell.tile) c.flat++;
    if (cell.cube != null) {
      if (cell.cube === shortTop) c.short++;
      else if (cell.cube === tallTop) c.tall++;
      else throw new Error(`unknown cube height ${cell.cube} (expected ${shortTop}/${tallTop})`);
    }
    if (cell.tunnel) c.tunnel++;
  }
  return c;
}
