import { validateLevel, expectedCounts } from './level-contract.mjs';
import {
  createSourceDiscovery,
  isStarterCourseId,
  sourceManifestEntryForRoadIndex,
} from './content-manifest.js';
import {
  STARTER_COURSE_IDS,
  createStarterCourse,
  starterCourseSelection,
} from './starter-cup.js';
import { createTutorialLevel, TUTORIAL_LEVEL_ID } from './tutorial-level.js';
export { expectedCounts } from './level-contract.mjs';

// loader.js — fetch exported level JSON (MERGER-PLAN §3). Generated by:
//   cargo run -p skyroads-cli -- export-json . web/assets
// web/assets is git-ignored (see NOTICE); the Starter Cup is tracked source, not exported data.

export async function loadIndex() {
  const res = await fetch('./assets/levels/index.json');
  if (!res.ok) throw new Error(`levels/index.json ${res.status} — run scripts/build-web.sh first`);
  return res.json();
}

export async function probeSourceCatalog() {
  try {
    const index = await loadIndex();
    return { ok: true, index, discovery: createSourceDiscovery(index), error: null };
  } catch (error) {
    return { ok: false, index: null, discovery: createSourceDiscovery(null), error };
  }
}

export async function loadLevel(file) {
  const res = await fetch(`./assets/levels/${file}`);
  if (!res.ok) throw new Error(`${file} ${res.status}`);
  const level = await res.json();
  validateLevel(level);
  return level;
}

export function selectRequestedLevel(index, search = globalThis.location?.search ?? '') {
  const params = new URLSearchParams(search);
  if (!params.has('level')) {
    const requestedCourse = params.get('course') ?? STARTER_COURSE_IDS.TRAINING;
    return starterCourseSelection(isStarterCourseId(requestedCourse) ? requestedCourse : STARTER_COURSE_IDS.TRAINING);
  }

  if (!Array.isArray(index.levels) || index.levels.length === 0) {
    throw new Error('levels/index.json has no levels — re-run the exporter');
  }

  const raw = params.get('level');
  const want = Number(raw);
  const exported = Number.isInteger(want) ? index.levels.find(l => l.roadIndex === want) : null;
  const manifestEntry = Number.isInteger(want) ? sourceManifestEntryForRoadIndex(want) : null;
  if (!exported || !manifestEntry) {
    console.warn(`?level=${raw} not in source corpus — loading the training run`);
    return starterCourseSelection(STARTER_COURSE_IDS.TRAINING);
  }
  return {
    type: 'source',
    entry: {
      ...manifestEntry,
      file: exported.file,
      exportedName: exported.name ?? null,
      available: true,
      disabled: false,
      disabledReason: null,
    },
  };
}

export function tutorialSelection() {
  return starterCourseSelection(TUTORIAL_LEVEL_ID);
}

export function starterSelection(courseId = STARTER_COURSE_IDS.TRAINING) {
  return starterCourseSelection(courseId);
}

export function isSourceLevelRequest(search = globalThis.location?.search ?? '') {
  return new URLSearchParams(search).has('level');
}

export function shouldProbeSourceCatalog(search = globalThis.location?.search ?? '') {
  const params = new URLSearchParams(search);
  if (params.has('level')) return true;
  const value = params.get('byo') ?? params.get('source');
  return value === '1' || value === 'true' || value === 'yes';
}

export async function loadTutorialLevel() {
  const level = validateLevel(createTutorialLevel(), { sourceCorpus: false });
  return { index: null, entry: tutorialSelection().entry, level, sourceKind: 'starter', courseId: TUTORIAL_LEVEL_ID };
}

export async function loadStarterCourse(courseId = STARTER_COURSE_IDS.TRAINING) {
  const level = validateLevel(createStarterCourse(courseId), { sourceCorpus: false });
  return { index: null, entry: starterSelection(courseId).entry, level, sourceKind: 'starter', courseId };
}

/** Pick tracked Starter Cup course at root/?course=..., or exact exported source road from ?level=0..30. */
export async function loadRequestedLevel(search = globalThis.location?.search ?? '') {
  if (!isSourceLevelRequest(search)) {
    const selected = selectRequestedLevel({ levels: [] }, search);
    return loadStarterCourse(selected.entry.id);
  }
  const idx = await loadIndex();
  const selected = selectRequestedLevel(idx, search);
  if (selected.type === 'starter') {
    const loaded = await loadStarterCourse(selected.entry.id);
    return { ...loaded, index: idx };
  }
  const level = await loadLevel(selected.entry.file);
  return { index: idx, entry: selected.entry, level, sourceKind: 'source', courseId: selected.entry.id };
}
